import '@/styles/globals.css'
import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'
import Head from 'next/head'
import Link from 'next/link'
import EmailIcon from '@mui/icons-material/Email'
import { AccountBox } from '@mui/icons-material'
import type { AppProps } from 'next/app'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='sidebar'>
        <Link href='/'>
          <EmailIcon />
        </Link>
        <Link href='/leads'>
          <AccountBox />
        </Link>
      </div>
      <main>
        <Component {...pageProps} />
      </main>
    </>
  )
}
